# .github/workflows/docker.yml

name: Build Docker image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Se connecter à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build de l'image
        run: |
          docker build \
            -t ${{ vars.DOCKERHUB_USERNAME }}/frenchcab-gateway:${{ github.sha }} \
            -t ${{ vars.DOCKERHUB_USERNAME }}/frenchcab-gateway:latest \
            .

      - name: Push vers Docker Hub
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/frenchcab-gateway:${{ github.sha }}
          docker push ${{ vars.DOCKERHUB_USERNAME }}/frenchcab-gateway:latest